/opt/homebrew/bin/arm-none-eabi-g++
-DFREE_RTOS_KERNEL_SMP=1
-DLIBRARY_LOG_LEVEL=LOG_ERROR
-DLIBRARY_LOG_NAME=\"PICOW_WSCLIENT\"
-DLIB_BOOT_STAGE2_HEADERS=1
-DLIB_FREERTOS_KERNEL=1
-DLIB_PICO_ATOMIC=1
-DLIB_PICO_BIT_OPS=1
-DLIB_PICO_BIT_OPS_PICO=1
-DLIB_PICO_CLIB_INTERFACE=1
-DLIB_PICO_CRT0=1
-DLIB_PICO_CXX_OPTIONS=1
-DLIB_PICO_DIVIDER=1
-DLIB_PICO_DIVIDER_COMPILER=1
-DLIB_PICO_DOUBLE=1
-DLIB_PICO_DOUBLE_PICO=1
-DLIB_PICO_FLASH=1
-DLIB_PICO_FLOAT=1
-DLIB_PICO_FLOAT_PICO=1
-DLIB_PICO_FLOAT_PICO_VFP=1
-DLIB_PICO_INT64_OPS=1
-DLIB_PICO_INT64_OPS_COMPILER=1
-DLIB_PICO_MALLOC=1
-DLIB_PICO_MEM_OPS=1
-DLIB_PICO_MEM_OPS_COMPILER=1
-DLIB_PICO_MULTICORE=1
-DLIB_PICO_NEWLIB_INTERFACE=1
-DLIB_PICO_PLATFORM=1
-DLIB_PICO_PLATFORM_COMPILER=1
-DLIB_PICO_PLATFORM_PANIC=1
-DLIB_PICO_PLATFORM_SECTIONS=1
-DLIB_PICO_PRINTF=1
-DLIB_PICO_PRINTF_PICO=1
-DLIB_PICO_RUNTIME=1
-DLIB_PICO_RUNTIME_INIT=1
-DLIB_PICO_STANDARD_BINARY_INFO=1
-DLIB_PICO_STANDARD_LINK=1
-DLIB_PICO_STDIO=1
-DLIB_PICO_STDIO_UART=1
-DLIB_PICO_STDLIB=1
-DLIB_PICO_SYNC=1
-DLIB_PICO_SYNC_CRITICAL_SECTION=1
-DLIB_PICO_SYNC_MUTEX=1
-DLIB_PICO_SYNC_SEM=1
-DLIB_PICO_TIME=1
-DLIB_PICO_TIME_ADAPTER=1
-DLIB_PICO_UTIL=1
-DNO_WRITEV=1
-DPICO_32BIT=1
-DPICO_BOARD=\"pimoroni_pico_plus2_rm2\"
-DPICO_BUILD=1
-DPICO_CMAKE_BUILD_TYPE=\"Release\"
-DPICO_CONFIG_RTOS_ADAPTER_HEADER=/Users/jondurrant/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure/freertos_sdk_config.h
-DPICO_COPY_TO_RAM=0
-DPICO_CXX_ENABLE_EXCEPTIONS=1
-DPICO_NO_FLASH=0
-DPICO_NO_HARDWARE=0
-DPICO_ON_DEVICE=1
-DPICO_RP2350=1
-DPICO_USE_BLOCKED_RAM=0
-DUSE_WOLF_ARM_STARTUP=1
-DWOLFSSL_LWIP=1
-DWOLFSSL_USER_SETTINGS=1
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/port/FreeRTOS-Kernel
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/../../lib/RPIPicoWWSClient-RTOS/src
-I/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_atomic/include
-I/Users/jondurrant/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/non_secure
-I/Users/jondurrant/pico/FreeRTOS-Kernel/include
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/port/lwip
-I/Users/jondurrant/src/RPIRM2Exp/lib/RPIPicoWWSClient-RTOS/lib/coreHTTP/source/include
-I/Users/jondurrant/src/RPIRM2Exp/lib/RPIPicoWWSClient-RTOS/lib/coreHTTP/source/interface
-I/Users/jondurrant/src/RPIRM2Exp/lib/RPIPicoWWSClient-RTOS/lib/coreHTTP/source/dependency/3rdparty/llhttp/include
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/port/coreHTTP
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/../../lib/RPIPicoWWSClient-RTOS/lib/uri-library
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/../../lib/RPIPicoWWSClient-RTOS/lib/wolfssl
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/port/wolfssl
-I/Users/jondurrant/pico/pico-sdk-2.1.0/lib/lwip/src/include/compat/posix
-I/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/../../lib/RPIPicoWWSClient-RTOS/lib/json-maker/src/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_stdlib_headers/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_gpio/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_base_headers/include
-isystem
/Users/jondurrant/src/RPIRM2Exp/exp/Pico2Plus/build/generated/pico_base
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/boards/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2350/pico_platform/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2350/hardware_regs/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_base/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_platform_compiler/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_platform_panic/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_platform_sections/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_dcp/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2350/hardware_structs/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_rcp/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/hardware_claim/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_sync/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_sync_spin_lock/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_irq/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_uart/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_resets/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_clocks/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_pll/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_vreg/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_watchdog/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_ticks/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_bootrom/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/boot_picoboot_headers/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/boot_bootrom_headers/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_boot_lock/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_flash/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_time/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_timer/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_sync/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_util/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_time_adapter/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_xosc/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_divider/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_runtime/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_runtime_init/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_bit_ops_headers/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_divider_headers/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_double/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_float/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_malloc/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/pico_binary_info/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_printf/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_stdio/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_stdio_uart/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/pico_multicore/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/common/boot_picobin_headers/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2350/boot_stage2/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_exception/include
-isystem
/Users/jondurrant/pico/pico-sdk-2.1.0/src/rp2_common/hardware_adc/include
-mcpu=cortex-m33
-mthumb
-march=armv8-m.main+fp+dsp
-mfloat-abi=softfp
-mcmse
-g
-O3
-DNDEBUG
-std=gnu++17
-fno-rtti
-fno-use-cxa-atexit
-ffunction-sections
-fdata-sections
-MD
-MT
CMakeFiles/picow_wsclient.dir/Users/jondurrant/src/RPIRM2Exp/lib/RPIPicoWWSClient-RTOS/src/Request.cpp.o
-MF
CMakeFiles/picow_wsclient.dir/Users/jondurrant/src/RPIRM2Exp/lib/RPIPicoWWSClient-RTOS/src/Request.cpp.o.d
-o
CMakeFiles/picow_wsclient.dir/Users/jondurrant/src/RPIRM2Exp/lib/RPIPicoWWSClient-RTOS/src/Request.cpp.o
-c
/Users/jondurrant/src/RPIRM2Exp/lib/RPIPicoWWSClient-RTOS/src/Request.cpp
